# Q1

In [1]:
import pandas as pd 
import numpy as np 
import seaborn as sns 
from scipy import stats
from scipy.stats import norm

In [2]:
data = pd.read_csv("Cutlets.csv")
data.head()

Unit A  Unit B
0  6.8090  6.7703
1  6.4376  7.5093
2  6.9157  6.7300
3  7.3012  6.7878
4  7.4488  7.1522

In [3]:
unitA = pd.Series(data.iloc[:,0])
unitA.head()

0    6.8090
1    6.4376
2    6.9157
3    7.3012
4    7.4488
Name: Unit A, dtype: float64

In [4]:
unitB = pd.Series(data.iloc[:,1])
unitB.head()

0    6.7703
1    7.5093
2    6.7300
3    6.7878
4    7.1522
Name: Unit B, dtype: float64

In [5]:
p_values = stats.ttest_ind(unitA,unitB)
p_values

Ttest_indResult(statistic=0.7228688704678063, pvalue=0.4722394724599501)

In [6]:
p_values[1] # compare p_value with α = 0.05 (At 5% significance level)

0.4722394724599501

In [7]:
#Since pvalue = 0.4722 > 0.05
#We do not reject Null Hypothesis

# Q2

In [8]:
data1 = pd.read_csv("LabTAT.csv")
data1.head()

Laboratory 1  Laboratory 2  Laboratory 3  Laboratory 4
0        185.35        165.53        176.70        166.13
1        170.49        185.91        198.45        160.79
2        192.77        194.92        201.23        185.18
3        177.33        183.00        199.61        176.42
4        193.41        169.57        204.63        152.60

In [9]:
p_value=stats.f_oneway(data1.iloc[:,0],data1.iloc[:,1],data1.iloc[:,2],data1.iloc[:,3]) # Anova ftest statistics
p_value

F_onewayResult(statistic=118.70421654401437, pvalue=2.1156708949992414e-57)

In [10]:
p_value[1]  # compare it with α = 0.05

2.1156708949992414e-57

In [11]:
#Since pvalue = 2.115 < 0.05
#We accept Alternative Hypothesis

# Q3

In [12]:
#H0 ->product sales ratio are same for males and females
#Ha ->product sales ratio are not same for males and females



In [13]:
from scipy.stats import chi2_contingency 
import scipy.stats as stats
data=[[50,142,131,70],[550,351,480,350]]
m=chi2_contingency(data)
m

(80.27295426602495,
 2.682172557281901e-17,
 3,
 array([[111.01694915,  91.21892655, 113.05225989,  77.71186441],
        [488.98305085, 401.78107345, 497.94774011, 342.28813559]]))

In [14]:
#Since pvalue = 2.68 < 0.05
#Reject Null Hypothesis

# Q4

from scipy.stats import chi2_contingency

In [15]:
data3 = pd.read_csv("Costomer+OrderForm.csv")
data3.head()

Phillippines   Indonesia       Malta       India
0   Error Free  Error Free   Defective  Error Free
1   Error Free  Error Free  Error Free   Defective
2   Error Free   Defective   Defective  Error Free
3   Error Free  Error Free  Error Free  Error Free
4   Error Free  Error Free   Defective  Error Free

In [16]:
data3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype 
---  ------        --------------  ----- 
 0   Phillippines  300 non-null    object
 1   Indonesia     300 non-null    object
 2   Malta         300 non-null    object
 3   India         300 non-null    object
dtypes: object(4)
memory usage: 9.5+ KB


In [17]:
data3.Phillippines.value_counts()

Error Free    271
Defective      29
Name: Phillippines, dtype: int64

In [18]:
data3.Indonesia.value_counts()

Error Free    267
Defective      33
Name: Indonesia, dtype: int64

In [19]:
data3.Malta.value_counts()

Error Free    269
Defective      31
Name: Malta, dtype: int64

In [20]:
data3.India.value_counts()

Error Free    280
Defective      20
Name: India, dtype: int64

In [21]:
obs=np.array([[271,267,269,280],[29,33,31,20]]) # Contingency table
obs

array([[271, 267, 269, 280],
       [ 29,  33,  31,  20]])

In [22]:
chi2_contingency(obs) # # Chi2 contengency independence test

(3.858960685820355,
 0.2771020991233135,
 3,
 array([[271.75, 271.75, 271.75, 271.75],
        [ 28.25,  28.25,  28.25,  28.25]]))

In [23]:
 #Compare p_value with α = 0.05

In [24]:
#Since pvalue = 0.277 > 0.05
#Do not reject Null Hypothesis

# Q5

In [25]:
data4= pd.read_csv("BuyerRatio.csv")

In [26]:
data4.head()

Observed Values  East  West  North  South
0           Males    50   142    131     70
1         Females   435  1523   1356    750

In [27]:
ratio=np.array([[50,142,131,70],[435,1523,1356,750]])
ratio

array([[  50,  142,  131,   70],
       [ 435, 1523, 1356,  750]])

In [28]:
chi2_contingency(ratio)

(1.595945538661058,
 0.6603094907091882,
 3,
 array([[  42.76531299,  146.81287862,  131.11756787,   72.30424052],
        [ 442.23468701, 1518.18712138, 1355.88243213,  747.69575948]]))

In [29]:
# p value= 0.6603 > 0.05, so Null Hypothesis